version: '3.9'
services:
  backend:
    image: le2sky/oleunaelim-production-server
    container_name: le2sky/oleunaelim-production-server
    ports:
      - 8080:3000
    volumes:
      - .:/app
    networks:
      - oleunaelim
    environment:
      - TZ=Asia/Seoul
    env_file:
      - src/config/env/.production.env
networks:
  oleunaelim:
