version: '3.9'
services:
  backend:
    image: le2sky/oleunaelim-production-server
    container_name: oleunaelim-production-server
    ports:
      - 80:3000
    networks:
      - oleunaelim
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
networks:
  oleunaelim:
