version: '3.9'
services:
  backend:
    image: le2sky/oleunaelim-develop-server
    container_name: oleunaelim-develop-server
    ports:
      - 80:${PORT}
    depends_on:
      - db
    networks:
      - oleunaelim
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: oleunaelim-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Asia/Seoul
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - oleunaelim

networks:
  oleunaelim:
